### ISSUE TITLE
solution branch has syntax errors

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/mongodb-intro#14]
update people.js misses some {}

**Comment by payne-chris-r** [comment]
Confirmed. Thanks @esthercordova.

**Comment by RealWeeks** [comment]
Noted, will update with new solution post-training

**Comment by RealWeeks** [comment]
Rebase update in commit 4fbf25fb04d6cc8fc7355c3ae6cdd5edf55d1c44.  Closing.
