### ISSUE TITLE
Solution Branch should be rebased off master.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/mongodb-intro#15]
@J-Weeks added this solution branch based off of last cohorts' lesson late last night and I didn't have time to rebase it off master. (Master now ahead of Solution)

**Comment by RealWeeks** [comment]
@payne-chris-r resolved in commit 4fbf25f

**Comment by gaand** [comment]
This solution did not respect issue #10, so work still needs to be done.

@J-Weeks

**Comment by RealWeeks** [comment]
@gaand  I'll put it on top of the current solution.

**Comment by RealWeeks** [comment]
@gaand commit efaa08b resolves both okay to close?

**Comment by berziiii** [comment]
see issue #16
