### ISSUE TITLE
Change domain of tables to match Rails/SQL domains

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/mongodb-intro#17]
From @gaand during @J-Weeks's lesson

**Comment by jrhorn424** [comment]
In progress. Solution branch will be stale and should be based off of 014/training in the future.

**Comment by gaand** [comment]
:white_check_mark:

**Comment by berziiii** [comment]
addressed in commit fcd7c931cc9c87917ace4fa3ab000703938cd270

**Comment by neugierige** [comment]
ok to close? I don't have permission

@gaand @jrhorn424 @payne-chris-r
