### ISSUE TITLE
incorrect remove script

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/mongodb-intro#18]
On solution in `scripts/remove/people.js`

change to 

`db.people.remove({surname:"Jason", gender:"m"})`

**Comment by gaand** [comment]
We really need to refactor things to use family_name (or familyName) so that Jason isn't confused.

**Comment by berziiii** [comment]
addressed in commit 7fc57fabdf42443ddbe272d15fbbd89113327fed

**Comment by neugierige** [comment]
can this be closed now? something's going on with my permissions

@gaand @payne-chris-r
