### ISSUE TITLE
remove first two commands

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/mongodb-intro#8]

**Comment by RealWeeks** [comment]
addressed in commit 4d58ae3

**Comment by gaand** [comment]
I'm not sure what this issue is about, but I am sure it's not addressed by the commit you mention.

@J-Weeks

**Comment by payne-chris-r** [comment]
@gaand @J-Weeks I'm not sure what you're referring to here. It worked fine for me. I'll report back if we have issues during delivery.

**Comment by RealWeeks** [comment]
@gaand I think this was in reference to installing mongodb. It's either resolved or unhelpful because I don't remember what this issue is about.
